### ISSUE TITLE
Wrong link 

### ISSUE THREAD

**Issue by iNoSec** [DarkStar7471/darkstar7471.com#1]
Hi and before starting, thanks to you and the tryhackme team for the platform!!!

Just to let you know, in the resources.html the link for Red Primer - Metasploit OVA's file is not the good one, he goes to Ice.7z file in your drive ;)

I cant make a pull request because i havent the link ;)

have a nice day

**Comment by DarkStar7471** [comment]
I'm glad you mentioned this! Ice is actually the virtual machine I used in the RP: Metasploit room as I've introduced some lovely vulnerabilities into the machine. I'll add a note on both TryHackMe and darkstar7471.com regarding this just to avoid any future confusion
