### ISSUE TITLE
OVA file is missed

### ISSUE THREAD

**Issue by zjhiphop** [DarkStar7471/darkstar7471.com#3]
The following OVA file is missed:

https://www.darkstar7471.com/downloads/ctf-vms/Blue.7z
https://www.darkstar7471.com/downloads/ctf-vms/Ignite.ova
https://www.darkstar7471.com/downloads/ctf-vms/JoyStick.ova

**Comment by andreiverse** [comment]
Bump.

**Comment by DarkStar7471** [comment]
Resolved! Just updated the site, had to finish a migration between hosting platforms!
